//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCaso14_Directiva.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        WebCaso14_Directiva.ServiceReference1.CompositeType GetDataUsingDataContract(WebCaso14_Directiva.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarResidente", ReplyAction="http://tempuri.org/IService1/ListarResidenteResponse")]
        string ListarResidente();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/NOMBRE_ARCHIVO_PAGO_OFFLINE_2", ReplyAction="http://tempuri.org/IService1/NOMBRE_ARCHIVO_PAGO_OFFLINE_2Response")]
        string NOMBRE_ARCHIVO_PAGO_OFFLINE_2();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_PAGO_OFFLINE", ReplyAction="http://tempuri.org/IService1/SP_PAGO_OFFLINEResponse")]
        string SP_PAGO_OFFLINE(string RUTResidente, string Tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ValidarLogin", ReplyAction="http://tempuri.org/IService1/ValidarLoginResponse")]
        bool ValidarLogin(string LOGusuario, string LOGpassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ValidarRut", ReplyAction="http://tempuri.org/IService1/ValidarRutResponse")]
        bool ValidarRut(string RutIngresado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ID_desde_LogUser", ReplyAction="http://tempuri.org/IService1/ID_desde_LogUserResponse")]
        int ID_desde_LogUser(string LOGusuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Nombre_desde_LogUser", ReplyAction="http://tempuri.org/IService1/Nombre_desde_LogUserResponse")]
        string Nombre_desde_LogUser(string LOGusuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CargoEnDirectiva", ReplyAction="http://tempuri.org/IService1/CargoEnDirectivaResponse")]
        string CargoEnDirectiva(string LOGusuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateResidente", ReplyAction="http://tempuri.org/IService1/CreateResidenteResponse")]
        bool CreateResidente(string Rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteResidente", ReplyAction="http://tempuri.org/IService1/DeleteResidenteResponse")]
        bool DeleteResidente(string Rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listar_Registros_GC_Residentes", ReplyAction="http://tempuri.org/IService1/listar_Registros_GC_ResidentesResponse")]
        string listar_Registros_GC_Residentes(string seleccionado, int idCondominio, string rutBuscar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/rectificar_Registros_GC_Residentes", ReplyAction="http://tempuri.org/IService1/rectificar_Registros_GC_ResidentesResponse")]
        string rectificar_Registros_GC_Residentes(string fechaPago, string estado, int monto, int idCuota);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Id_Condominio_desde_rut", ReplyAction="http://tempuri.org/IService1/Id_Condominio_desde_rutResponse")]
        int Id_Condominio_desde_rut(string select, string rutBuscar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listar_Multas_Residentes", ReplyAction="http://tempuri.org/IService1/listar_Multas_ResidentesResponse")]
        string listar_Multas_Residentes(string select, int idCondominio, string rutBuscar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Crear_Multa", ReplyAction="http://tempuri.org/IService1/Crear_MultaResponse")]
        string Crear_Multa(int monto, string descripcion, string rutMultar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Met_Ver_Detalle_Reservas", ReplyAction="http://tempuri.org/IService1/Met_Ver_Detalle_ReservasResponse")]
        string Met_Ver_Detalle_Reservas(string select, string rutResidente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Modificar_Multa", ReplyAction="http://tempuri.org/IService1/Modificar_MultaResponse")]
        string Modificar_Multa(string fechapago, int monto, string descripcion, string estado, int idMulta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Ingresar_Observaciones", ReplyAction="http://tempuri.org/IService1/Ingresar_ObservacionesResponse")]
        string Ingresar_Observaciones(string observacion, int idGastoComun);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listar_Anuncios", ReplyAction="http://tempuri.org/IService1/listar_AnunciosResponse")]
        string listar_Anuncios(int idCondominio, int lugar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Residente_Nivel_Acceso", ReplyAction="http://tempuri.org/IService1/Residente_Nivel_AccesoResponse")]
        int Residente_Nivel_Acceso(string LOGusuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GenerarAlertasMora", ReplyAction="http://tempuri.org/IService1/GenerarAlertasMoraResponse")]
        int GenerarAlertasMora(string RutIngresado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GenerarAlertasMulta", ReplyAction="http://tempuri.org/IService1/GenerarAlertasMultaResponse")]
        int GenerarAlertasMulta(string RutIngresado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Listar_Pago_Offline", ReplyAction="http://tempuri.org/IService1/Listar_Pago_OfflineResponse")]
        string Listar_Pago_Offline(string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ValidarTarjeta", ReplyAction="http://tempuri.org/IService1/ValidarTarjetaResponse")]
        bool ValidarTarjeta(string RutIngresado, long numeroTarjeta, int codigoSeg, string FechaV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Met_Pagar_Reservas", ReplyAction="http://tempuri.org/IService1/Met_Pagar_ReservasResponse")]
        string Met_Pagar_Reservas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Listar_Pagos_Residente", ReplyAction="http://tempuri.org/IService1/Listar_Pagos_ResidenteResponse")]
        string Listar_Pagos_Residente(string rutResidente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarReportes", ReplyAction="http://tempuri.org/IService1/ListarReportesResponse")]
        string ListarReportes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Listar_Cuota_Gasto_Residentes", ReplyAction="http://tempuri.org/IService1/Listar_Cuota_Gasto_ResidentesResponse")]
        string Listar_Cuota_Gasto_Residentes(int idCondominio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarMultas", ReplyAction="http://tempuri.org/IService1/ListarMultasResponse")]
        string ListarMultas(int idCondominio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarMultasPorResidnte", ReplyAction="http://tempuri.org/IService1/ListarMultasPorResidnteResponse")]
        string ListarMultasPorResidnte(int idCondominio, string rut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarEventoLibro", ReplyAction="http://tempuri.org/IService1/ListarEventoLibroResponse")]
        string ListarEventoLibro(int id_Condominio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarIngresoAdministracion", ReplyAction="http://tempuri.org/IService1/ListarIngresoAdministracionResponse")]
        string ListarIngresoAdministracion(string filtroFecha, string fechaMax, int id_Condominio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarIngresoAdministracionTodo", ReplyAction="http://tempuri.org/IService1/ListarIngresoAdministracionTodoResponse")]
        string ListarIngresoAdministracionTodo(int id_Condominio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_Crear_Ingreso_Gasto_Comun", ReplyAction="http://tempuri.org/IService1/SP_Crear_Ingreso_Gasto_ComunResponse")]
        string SP_Crear_Ingreso_Gasto_Comun(string _tipo, string _categoria, string _descripcion, int _monto, int _id_condominio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_Modificar_Ingreso_Gasto_Comun", ReplyAction="http://tempuri.org/IService1/SP_Modificar_Ingreso_Gasto_ComunResponse")]
        string SP_Modificar_Ingreso_Gasto_Comun(int _idadministrar, string _tipo, string _categoria, string _descripcion, int _monto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listar_Registros_GC_Mensuales", ReplyAction="http://tempuri.org/IService1/listar_Registros_GC_MensualesResponse")]
        string listar_Registros_GC_Mensuales(string seleccionado, int idCondominio, int mes, int anio, string categoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Calcular_Total_Mensual_Registros_GC", ReplyAction="http://tempuri.org/IService1/Calcular_Total_Mensual_Registros_GCResponse")]
        string Calcular_Total_Mensual_Registros_GC(int idCondominio, int mes, int anio, string entradaSalida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_Crear_Cuota_Gasto_Comun", ReplyAction="http://tempuri.org/IService1/SP_Crear_Cuota_Gasto_ComunResponse")]
        string SP_Crear_Cuota_Gasto_Comun(int _id_condominio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_Actualizar_Cuota_G_C", ReplyAction="http://tempuri.org/IService1/SP_Actualizar_Cuota_G_CResponse")]
        string SP_Actualizar_Cuota_G_C(int _id_condominio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listar_Morosos_Totales", ReplyAction="http://tempuri.org/IService1/listar_Morosos_TotalesResponse")]
        string listar_Morosos_Totales(string seleccionado, int idCondominio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_Crear_Reportes", ReplyAction="http://tempuri.org/IService1/SP_Crear_ReportesResponse")]
        string SP_Crear_Reportes(string Tipo, string DESCRIPCION, string RUT_REPORTADO, int id_condominio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listar_Correos_Residentes", ReplyAction="http://tempuri.org/IService1/listar_Correos_ResidentesResponse")]
        string listar_Correos_Residentes(int idCondominio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_Revisar_Multas", ReplyAction="http://tempuri.org/IService1/SP_Revisar_MultasResponse")]
        string SP_Revisar_Multas(int id_condominio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ValidarLoginFuncionario", ReplyAction="http://tempuri.org/IService1/ValidarLoginFuncionarioResponse")]
        bool ValidarLoginFuncionario(string LOGusuario, string LOGpassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ID_desde_LogUser_Funcionario", ReplyAction="http://tempuri.org/IService1/ID_desde_LogUser_FuncionarioResponse")]
        int ID_desde_LogUser_Funcionario(string LOGusuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Nombre_desde_LogUser_Funcionario", ReplyAction="http://tempuri.org/IService1/Nombre_desde_LogUser_FuncionarioResponse")]
        string Nombre_desde_LogUser_Funcionario(string LOGusuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CargoEnCondominio", ReplyAction="http://tempuri.org/IService1/CargoEnCondominioResponse")]
        string CargoEnCondominio(string LOGusuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/id_Condominio_desde_Funcionario", ReplyAction="http://tempuri.org/IService1/id_Condominio_desde_FuncionarioResponse")]
        int id_Condominio_desde_Funcionario(string LOGusuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_Crear_Anuncios", ReplyAction="http://tempuri.org/IService1/SP_Crear_AnunciosResponse")]
        string SP_Crear_Anuncios(string Titulo, string Detalle, int Condominio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_Crear_Residentes", ReplyAction="http://tempuri.org/IService1/SP_Crear_ResidentesResponse")]
        string SP_Crear_Residentes(string Rut_Residente, string Pass_Residente, string Nombre_Residente, string Direccion, string Correo, int ID_TIPO_RESIDENTE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_Deshabilitar_Residente", ReplyAction="http://tempuri.org/IService1/SP_Deshabilitar_ResidenteResponse")]
        string SP_Deshabilitar_Residente(string Rut_Residente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_Habilitar_Residente", ReplyAction="http://tempuri.org/IService1/SP_Habilitar_ResidenteResponse")]
        string SP_Habilitar_Residente(string Rut_Residente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_Crear_Evento_Libro", ReplyAction="http://tempuri.org/IService1/SP_Crear_Evento_LibroResponse")]
        string SP_Crear_Evento_Libro(string SP_Titulo, string SP_Descripcion, string SP_Area_Comun, string SP_Rut_Involucrado, string SP_Rut_Funcionario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarDetalleReserva", ReplyAction="http://tempuri.org/IService1/ListarDetalleReservaResponse")]
        string ListarDetalleReserva();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListarDetalleReservaPorFecha", ReplyAction="http://tempuri.org/IService1/ListarDetalleReservaPorFechaResponse")]
        string ListarDetalleReservaPorFecha(string _fecha_areservar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateDetalleReserva", ReplyAction="http://tempuri.org/IService1/CreateDetalleReservaResponse")]
        bool CreateDetalleReserva(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReadDetalleReserva", ReplyAction="http://tempuri.org/IService1/ReadDetalleReservaResponse")]
        string ReadDetalleReserva(int fechaSeleccionada);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_Crear_Detalle_Reserva", ReplyAction="http://tempuri.org/IService1/SP_Crear_Detalle_ReservaResponse")]
        bool SP_Crear_Detalle_Reserva(int idServicio, int tramo1, int tramo2, int tramo3, string fechaASeleccionar, string RUTResidente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_Crear_Reserva_Residente_Desde_Funcionario", ReplyAction="http://tempuri.org/IService1/SP_Crear_Reserva_Residente_Desde_FuncionarioResponse" +
            "")]
        bool SP_Crear_Reserva_Residente_Desde_Funcionario(string RUTResidente, string RUT_Funcionario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_Crear_Reserva_Residente", ReplyAction="http://tempuri.org/IService1/SP_Crear_Reserva_ResidenteResponse")]
        bool SP_Crear_Reserva_Residente(string RUTResidente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UsoDeTramoSegunFechayServicio", ReplyAction="http://tempuri.org/IService1/UsoDeTramoSegunFechayServicioResponse")]
        int UsoDeTramoSegunFechayServicio(string fecha, int tramo, int servicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/M_Capacidad_Servicio_porID", ReplyAction="http://tempuri.org/IService1/M_Capacidad_Servicio_porIDResponse")]
        int M_Capacidad_Servicio_porID(int Id_Busqueda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/M_Precio_Servicio_porID", ReplyAction="http://tempuri.org/IService1/M_Precio_Servicio_porIDResponse")]
        int M_Precio_Servicio_porID(int Id_Busqueda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ContarFilas", ReplyAction="http://tempuri.org/IService1/ContarFilasResponse")]
        int ContarFilas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SP_Pagar_Reservas_Tarjetas", ReplyAction="http://tempuri.org/IService1/SP_Pagar_Reservas_TarjetasResponse")]
        string SP_Pagar_Reservas_Tarjetas(string RUTResidente);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebCaso14_Directiva.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebCaso14_Directiva.ServiceReference1.IService1>, WebCaso14_Directiva.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public WebCaso14_Directiva.ServiceReference1.CompositeType GetDataUsingDataContract(WebCaso14_Directiva.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public string ListarResidente() {
            return base.Channel.ListarResidente();
        }
        
        public string NOMBRE_ARCHIVO_PAGO_OFFLINE_2() {
            return base.Channel.NOMBRE_ARCHIVO_PAGO_OFFLINE_2();
        }
        
        public string SP_PAGO_OFFLINE(string RUTResidente, string Tipo) {
            return base.Channel.SP_PAGO_OFFLINE(RUTResidente, Tipo);
        }
        
        public bool ValidarLogin(string LOGusuario, string LOGpassword) {
            return base.Channel.ValidarLogin(LOGusuario, LOGpassword);
        }
        
        public bool ValidarRut(string RutIngresado) {
            return base.Channel.ValidarRut(RutIngresado);
        }
        
        public int ID_desde_LogUser(string LOGusuario) {
            return base.Channel.ID_desde_LogUser(LOGusuario);
        }
        
        public string Nombre_desde_LogUser(string LOGusuario) {
            return base.Channel.Nombre_desde_LogUser(LOGusuario);
        }
        
        public string CargoEnDirectiva(string LOGusuario) {
            return base.Channel.CargoEnDirectiva(LOGusuario);
        }
        
        public bool CreateResidente(string Rut) {
            return base.Channel.CreateResidente(Rut);
        }
        
        public bool DeleteResidente(string Rut) {
            return base.Channel.DeleteResidente(Rut);
        }
        
        public string listar_Registros_GC_Residentes(string seleccionado, int idCondominio, string rutBuscar) {
            return base.Channel.listar_Registros_GC_Residentes(seleccionado, idCondominio, rutBuscar);
        }
        
        public string rectificar_Registros_GC_Residentes(string fechaPago, string estado, int monto, int idCuota) {
            return base.Channel.rectificar_Registros_GC_Residentes(fechaPago, estado, monto, idCuota);
        }
        
        public int Id_Condominio_desde_rut(string select, string rutBuscar) {
            return base.Channel.Id_Condominio_desde_rut(select, rutBuscar);
        }
        
        public string listar_Multas_Residentes(string select, int idCondominio, string rutBuscar) {
            return base.Channel.listar_Multas_Residentes(select, idCondominio, rutBuscar);
        }
        
        public string Crear_Multa(int monto, string descripcion, string rutMultar) {
            return base.Channel.Crear_Multa(monto, descripcion, rutMultar);
        }
        
        public string Met_Ver_Detalle_Reservas(string select, string rutResidente) {
            return base.Channel.Met_Ver_Detalle_Reservas(select, rutResidente);
        }
        
        public string Modificar_Multa(string fechapago, int monto, string descripcion, string estado, int idMulta) {
            return base.Channel.Modificar_Multa(fechapago, monto, descripcion, estado, idMulta);
        }
        
        public string Ingresar_Observaciones(string observacion, int idGastoComun) {
            return base.Channel.Ingresar_Observaciones(observacion, idGastoComun);
        }
        
        public string listar_Anuncios(int idCondominio, int lugar) {
            return base.Channel.listar_Anuncios(idCondominio, lugar);
        }
        
        public int Residente_Nivel_Acceso(string LOGusuario) {
            return base.Channel.Residente_Nivel_Acceso(LOGusuario);
        }
        
        public int GenerarAlertasMora(string RutIngresado) {
            return base.Channel.GenerarAlertasMora(RutIngresado);
        }
        
        public int GenerarAlertasMulta(string RutIngresado) {
            return base.Channel.GenerarAlertasMulta(RutIngresado);
        }
        
        public string Listar_Pago_Offline(string rut) {
            return base.Channel.Listar_Pago_Offline(rut);
        }
        
        public bool ValidarTarjeta(string RutIngresado, long numeroTarjeta, int codigoSeg, string FechaV) {
            return base.Channel.ValidarTarjeta(RutIngresado, numeroTarjeta, codigoSeg, FechaV);
        }
        
        public string Met_Pagar_Reservas() {
            return base.Channel.Met_Pagar_Reservas();
        }
        
        public string Listar_Pagos_Residente(string rutResidente) {
            return base.Channel.Listar_Pagos_Residente(rutResidente);
        }
        
        public string ListarReportes() {
            return base.Channel.ListarReportes();
        }
        
        public string Listar_Cuota_Gasto_Residentes(int idCondominio) {
            return base.Channel.Listar_Cuota_Gasto_Residentes(idCondominio);
        }
        
        public string ListarMultas(int idCondominio) {
            return base.Channel.ListarMultas(idCondominio);
        }
        
        public string ListarMultasPorResidnte(int idCondominio, string rut) {
            return base.Channel.ListarMultasPorResidnte(idCondominio, rut);
        }
        
        public string ListarEventoLibro(int id_Condominio) {
            return base.Channel.ListarEventoLibro(id_Condominio);
        }
        
        public string ListarIngresoAdministracion(string filtroFecha, string fechaMax, int id_Condominio) {
            return base.Channel.ListarIngresoAdministracion(filtroFecha, fechaMax, id_Condominio);
        }
        
        public string ListarIngresoAdministracionTodo(int id_Condominio) {
            return base.Channel.ListarIngresoAdministracionTodo(id_Condominio);
        }
        
        public string SP_Crear_Ingreso_Gasto_Comun(string _tipo, string _categoria, string _descripcion, int _monto, int _id_condominio) {
            return base.Channel.SP_Crear_Ingreso_Gasto_Comun(_tipo, _categoria, _descripcion, _monto, _id_condominio);
        }
        
        public string SP_Modificar_Ingreso_Gasto_Comun(int _idadministrar, string _tipo, string _categoria, string _descripcion, int _monto) {
            return base.Channel.SP_Modificar_Ingreso_Gasto_Comun(_idadministrar, _tipo, _categoria, _descripcion, _monto);
        }
        
        public string listar_Registros_GC_Mensuales(string seleccionado, int idCondominio, int mes, int anio, string categoria) {
            return base.Channel.listar_Registros_GC_Mensuales(seleccionado, idCondominio, mes, anio, categoria);
        }
        
        public string Calcular_Total_Mensual_Registros_GC(int idCondominio, int mes, int anio, string entradaSalida) {
            return base.Channel.Calcular_Total_Mensual_Registros_GC(idCondominio, mes, anio, entradaSalida);
        }
        
        public string SP_Crear_Cuota_Gasto_Comun(int _id_condominio) {
            return base.Channel.SP_Crear_Cuota_Gasto_Comun(_id_condominio);
        }
        
        public string SP_Actualizar_Cuota_G_C(int _id_condominio) {
            return base.Channel.SP_Actualizar_Cuota_G_C(_id_condominio);
        }
        
        public string listar_Morosos_Totales(string seleccionado, int idCondominio) {
            return base.Channel.listar_Morosos_Totales(seleccionado, idCondominio);
        }
        
        public string SP_Crear_Reportes(string Tipo, string DESCRIPCION, string RUT_REPORTADO, int id_condominio) {
            return base.Channel.SP_Crear_Reportes(Tipo, DESCRIPCION, RUT_REPORTADO, id_condominio);
        }
        
        public string listar_Correos_Residentes(int idCondominio) {
            return base.Channel.listar_Correos_Residentes(idCondominio);
        }
        
        public string SP_Revisar_Multas(int id_condominio) {
            return base.Channel.SP_Revisar_Multas(id_condominio);
        }
        
        public bool ValidarLoginFuncionario(string LOGusuario, string LOGpassword) {
            return base.Channel.ValidarLoginFuncionario(LOGusuario, LOGpassword);
        }
        
        public int ID_desde_LogUser_Funcionario(string LOGusuario) {
            return base.Channel.ID_desde_LogUser_Funcionario(LOGusuario);
        }
        
        public string Nombre_desde_LogUser_Funcionario(string LOGusuario) {
            return base.Channel.Nombre_desde_LogUser_Funcionario(LOGusuario);
        }
        
        public string CargoEnCondominio(string LOGusuario) {
            return base.Channel.CargoEnCondominio(LOGusuario);
        }
        
        public int id_Condominio_desde_Funcionario(string LOGusuario) {
            return base.Channel.id_Condominio_desde_Funcionario(LOGusuario);
        }
        
        public string SP_Crear_Anuncios(string Titulo, string Detalle, int Condominio) {
            return base.Channel.SP_Crear_Anuncios(Titulo, Detalle, Condominio);
        }
        
        public string SP_Crear_Residentes(string Rut_Residente, string Pass_Residente, string Nombre_Residente, string Direccion, string Correo, int ID_TIPO_RESIDENTE) {
            return base.Channel.SP_Crear_Residentes(Rut_Residente, Pass_Residente, Nombre_Residente, Direccion, Correo, ID_TIPO_RESIDENTE);
        }
        
        public string SP_Deshabilitar_Residente(string Rut_Residente) {
            return base.Channel.SP_Deshabilitar_Residente(Rut_Residente);
        }
        
        public string SP_Habilitar_Residente(string Rut_Residente) {
            return base.Channel.SP_Habilitar_Residente(Rut_Residente);
        }
        
        public string SP_Crear_Evento_Libro(string SP_Titulo, string SP_Descripcion, string SP_Area_Comun, string SP_Rut_Involucrado, string SP_Rut_Funcionario) {
            return base.Channel.SP_Crear_Evento_Libro(SP_Titulo, SP_Descripcion, SP_Area_Comun, SP_Rut_Involucrado, SP_Rut_Funcionario);
        }
        
        public string ListarDetalleReserva() {
            return base.Channel.ListarDetalleReserva();
        }
        
        public string ListarDetalleReservaPorFecha(string _fecha_areservar) {
            return base.Channel.ListarDetalleReservaPorFecha(_fecha_areservar);
        }
        
        public bool CreateDetalleReserva(string id) {
            return base.Channel.CreateDetalleReserva(id);
        }
        
        public string ReadDetalleReserva(int fechaSeleccionada) {
            return base.Channel.ReadDetalleReserva(fechaSeleccionada);
        }
        
        public bool SP_Crear_Detalle_Reserva(int idServicio, int tramo1, int tramo2, int tramo3, string fechaASeleccionar, string RUTResidente) {
            return base.Channel.SP_Crear_Detalle_Reserva(idServicio, tramo1, tramo2, tramo3, fechaASeleccionar, RUTResidente);
        }
        
        public bool SP_Crear_Reserva_Residente_Desde_Funcionario(string RUTResidente, string RUT_Funcionario) {
            return base.Channel.SP_Crear_Reserva_Residente_Desde_Funcionario(RUTResidente, RUT_Funcionario);
        }
        
        public bool SP_Crear_Reserva_Residente(string RUTResidente) {
            return base.Channel.SP_Crear_Reserva_Residente(RUTResidente);
        }
        
        public int UsoDeTramoSegunFechayServicio(string fecha, int tramo, int servicio) {
            return base.Channel.UsoDeTramoSegunFechayServicio(fecha, tramo, servicio);
        }
        
        public int M_Capacidad_Servicio_porID(int Id_Busqueda) {
            return base.Channel.M_Capacidad_Servicio_porID(Id_Busqueda);
        }
        
        public int M_Precio_Servicio_porID(int Id_Busqueda) {
            return base.Channel.M_Precio_Servicio_porID(Id_Busqueda);
        }
        
        public int ContarFilas() {
            return base.Channel.ContarFilas();
        }
        
        public string SP_Pagar_Reservas_Tarjetas(string RUTResidente) {
            return base.Channel.SP_Pagar_Reservas_Tarjetas(RUTResidente);
        }
    }
}
